ticketee/config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    resources :projects, only: [] do
      resources :tickets
    end
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]
end

ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"
  belongs_to :state
  has_many :attachments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, uniq: true
  has_and_belongs_to_many :watchers, join_table: "ticket_watchers",
    class_name: "User", uniq: true

  attr_accessor :tag_names

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  before_create :assign_default_state
  after_create :author_watches_me

  searcher do
    label :tag, from: :tags, field: "name"
    label :state, from: :state, field: "name"
  end

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_initialize_by(name: name)
    end
  end

  private

  def author_watches_me
    if author.present? && !self.watchers.include?(author)
      self.watchers << author
    end
  end

  def assign_default_state
    self.state ||= State.default
  end
end

ticketee/app/controllers/api/tickets_controller.rb
class API::TicketsController < API::ApplicationController
  attr_reader :current_user

  before_action :set_project

  def show
    @ticket = @project.tickets.find(params[:id])
    authorize @ticket, :show?
    render json: @ticket
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    authorize @ticket, :create?
    if @ticket.save
      render json: @ticket, status: 201
    else
      render json: { errors: @ticket.errors.full_messages }, status: 422
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

ticketee/app/controllers/api/v2/tickets.rb
require "sinatra"

module API
  module V2
    class Tickets < Sinatra::Base
      before do
        headers "Content-Type" => "text/json"
        set_user
        set_project
      end

      get "/:id" do
        ticket = @project.tickets.find(params[:id])
        unless TicketPolicy.new(@user, ticket).show?
          halt 404, "The ticket you were looking for could not be found."
        end
        TicketSerializer.new(ticket).to_json
      end

      private

      def set_project
        @project = Project.find(params[:project_id])
      end

      def set_user
        if env["HTTP_AUTHORIZATION"].present?
          if auth_token = /Token token=(.*)/.match(env["HTTP_AUTHORIZATION"])
            @user = User.find_by(api_key: auth_token[1])
            return @user if @user.present?
          end
        end

        unauthenticated!
      end

      def unauthenticated!
        halt 401, {error: "Unauthenticated"}.to_json
      end

      def params
        hash = env["action_dispatch.request.path_parameters"].merge!(super)
        HashWithIndifferentAccess.new(hash)
      end
    end
  end
end

ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :watch]

  def search
    authorize @project, :show?
    if params[:search].present?
      @tickets = @project.tickets.search(params[:search])
    else
      @tickets = @project.tickets
    end
    render "projects/show"
  end

  def new
    @ticket = @project.tickets.build
    authorize @ticket, :create?
    @ticket.attachments.build
  end

  def create
    @ticket = @project.tickets.new

    whitelisted_params = ticket_params
    unless policy(@ticket).tag?
      whitelisted_params.delete(:tag_names)
    end

    @ticket.attributes = whitelisted_params
    @ticket.author = current_user
    authorize @ticket, :create?

    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show
    authorize @ticket, :show?
    @comment = @ticket.comments.build(state_id: @ticket.state_id)
  end

  def edit
    authorize @ticket, :update?
  end

  def update
    authorize @ticket, :update?
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    authorize @ticket, :destroy?
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."

    redirect_to @project
  end

  def watch
    authorize @ticket, :show?
    if @ticket.watchers.exists?(current_user.id)
      @ticket.watchers.destroy(current_user)
      flash[:notice] = "You are no longer watching this ticket."
    else
      @ticket.watchers << current_user
      flash[:notice] = "You are now watching this ticket."
    end

    redirect_to project_ticket_path(@ticket.project, @ticket)
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name, :description, :tag_names,
      attachments_attributes: [:file, :file_cache])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

ticketee/app/helpers/api/tickets_helper.rb
module API::TicketsHelper
end

ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
  def state_transition_for(comment)
    if comment.previous_state != comment.state
      content_tag(:p) do
        value = "<strong><i class='fa fa-gear'></i> state changed</strong>"
        if comment.previous_state.present?
          value += " from #{render comment.previous_state}"
        end
        value += " to #{render comment.state}"
        value.html_safe
      end
    end
  end

  def toggle_watching_button(ticket)
    text = if ticket.watchers.include?(current_user)
      "Unwatch"
    else
      "Watch"
    end
    link_to text, watch_project_ticket_path(ticket.project, ticket),
      class: text.parameterize, method: :post
  end
end

ticketee/app/views/tickets/_form.html.erb
<%= simple_form_for([project, ticket]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= render "tags/form", f: f %>

  <div id="attachments">
    <h3>Attachments</h3>
    <%= render partial: "attachments/form", locals: { f: f, index: 0 } %>
  </div>
  <p>
    <%= link_to "Add another file", new_attachment_path, remote: true,
      id: "add_file", data: { params: {index: ticket.attachments.size} } %>
  </p>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

ticketee/app/views/tickets/edit.html.erb
<header>
  <h1>
    Edit Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

ticketee/app/views/tickets/new.html.erb
<header>
  <h1>
    New Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

ticketee/app/views/tickets/show.html.erb
<div id="ticket">
  <header>
    <h1><%= @project.name %></h1>
  </header>

  <header>
    <h2><%= @ticket.name %></h2>

    <ul class="actions">
      <% if policy(@ticket).update? %>
        <li><%= link_to "Edit Ticket", [:edit, @project, @ticket],
          class: "edit" %></li>
      <% end %>
      <% if policy(@ticket).destroy? %>
        <li><%= link_to "Delete Ticket", [@project, @ticket],
          method: :delete,
          data: { confirm: "Are you sure you want to delete this ticket?" },
          class: "delete" %></li>
      <% end %>
    </ul>
  </header>

  <table id="attributes">
    <tr>
      <th>Author:</th>
      <td><%= @ticket.author.email %></td>
    </tr>
    <tr>
      <th>Created:</th>
      <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
    </tr>
    <% if @ticket.state.present? %>
      <tr>
        <th>State:</th>
        <td><%= render @ticket.state %></td>
      </tr>
    <% end %>
    <% if @ticket.tags.any? %>
      <tr id="tags">
        <th>Tags:</th>
        <td><%= render @ticket.tags, ticket: @ticket %></td>
      </tr>
    <% end %>
    <tr id="watchers">
      <th>Watchers:</th>
      <td>
        <%= toggle_watching_button(@ticket) %><br />
        <%= @ticket.watchers.map(&:email).to_sentence %>
      </td>
    </tr>
  </table>

  <%= simple_format(@ticket.description) %>

  <% if @ticket.attachments.any? %>
    <h4>Attachments</h4>
    <div class="attachments">
      <% @ticket.attachments.each do |attachment| %>
        <p>
          <%= link_to File.basename(attachment.file.url),
            attachment_path(attachment) %>
          (<%= number_to_human_size(attachment.file.size) %>)
        </p>
      <% end %>
    </div>
  <% end %>
</div>

<header>
  <h3>Comments</h3>
</header>

<div id="comments">
  <% if @ticket.comments.select(&:persisted?).any? %>
    <%= render @ticket.comments.select(&:persisted?) %>
  <% else %>
    <p>There are no comments for this ticket.</p>
  <% end %>
</div>

<% if policy(@comment).create? %>
  <%= render "comments/form", ticket: @ticket, comment: @comment %>
<% end %>