ticketee/config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    resources :projects, only: [] do
      resources :tickets
    end
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]
end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all

  validates :name, presence: true

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

ticketee/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created."
      render "new"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]

  def index
    @projects = policy_scope(Project)
  end

  def show
    authorize @project, :show?
    @tickets = @project.tickets
  end

  def edit
    authorize @project, :update?
  end

  def update
    authorize @project, :update?
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

ticketee/app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/views/projects/_form.html.erb
<%= simple_form_for(project) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

ticketee/app/views/projects/edit.html.erb
<header>
  <h1>Edit Project</h1>
</header>

<%= render "form", project: @project %>

ticketee/app/views/projects/index.html.erb
<header>
  <h1>Projects</h1>

  <% admins_only do %>
    <ul class="actions">
      <li>
        <%= link_to "New Project", new_admin_project_path, class: "new" %>
      </li>
    </ul>
  <% end %>
</header>

<div id="projects">
  <% @projects.each do |project| %>
    <h2><%= link_to project.name, project %></h2>
    <p><%= project.description %></p>
  <% end %>
</div>

ticketee/app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<header>
  <h1><%= @project.name %></h1>

  <ul class="actions">
    <% if policy(@project).update? %>
      <li><%= link_to "Edit Project", edit_project_path(@project),
        class: "edit" %></li>
    <% end %>
    <% admins_only do %>
      <li><%= link_to "Delete Project", admin_project_path(@project),
        method: :delete,
        data: { confirm: "Are you sure you want to delete this project?" },
        class: "delete" %></li>
    <% end %>
  </ul>
</header>

<p><%= @project.description %></p>

<header>
  <h2>Tickets</h2>

  <ul class="actions">
    <li>
      <%= form_tag search_project_tickets_path(@project), method: :get,
        class: "form-inline" do %>
        <%= label_tag "search", "Search", class: "sr-only" %>
        <%= text_field_tag "search", params[:search], class: "form-control" %>
        <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>
    </li>
    <% if policy(Ticket.new(project: @project)).create? %>
      <li><%= link_to "New Ticket", new_project_ticket_path(@project),
        class: "new" %></li>
    <% end %>
  </ul>
</header>

<ul id="tickets">
  <% @tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.name, [@project, ticket] %>
      <%= render ticket.state if ticket.state %>
    </li>
  <% end %>
</ul>