ticketee/config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    resources :projects, only: [] do
      resources :tickets
    end
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]
end

ticketee/app/models/user.rb
class User < ActiveRecord::Base
  has_many :roles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :excluding_archived, lambda { where(archived_at: nil) }

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def generate_api_key
    self.update_column(:api_key, SecureRandom.hex(16))
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

ticketee/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_projects, only: [:new, :create, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :archive]

  def index
    @users = User.excluding_archived.order(:email)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    build_roles_for(@user)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    User.transaction do
      @user.roles.clear
      build_roles_for(@user)

      if @user.update(user_params)
        flash[:notice] = "User has been updated."
        redirect_to admin_users_path
      else
        flash.now[:alert] = "User has not been updated."
        render "edit"
        raise ActiveRecord::Rollback
      end
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself!"
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end

    redirect_to admin_users_path
  end

  private

  def set_projects
    @projects = Project.order(:name)
  end

  def build_roles_for(user)
    role_data = params.fetch(:roles, [])
    role_data.each do |project_id, role_name|
      if role_name.present?
        user.roles.build(project_id: project_id, role: role_name)
      end
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

ticketee/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

ticketee/app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :admin, label: "Is an admin?" %>

  <header>
    <h2>Roles</h2>
  </header>

  <table class="roles">
    <% projects.each do |project| %>
      <tr>
        <th><%= label_tag dom_id(project), project.name %></th>
        <td>
          <%= select_tag dom_id(project), options_for_select(roles,
            user.role_on(project)), name: "roles[#{project.id}]",
            include_blank: true %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

ticketee/app/views/admin/users/edit.html.erb
<header>
  <h1>Edit User</h1>
</header>

<%= render "form", user: @user, projects: @projects %>

ticketee/app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>

  <ul class="actions">
    <li>
      <%= link_to "New User", new_admin_user_path, class: "new" %>
    </li>
  </ul>
</header>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

ticketee/app/views/admin/users/new.html.erb
<header>
  <h1>New User</h1>
</header>

<%= render "form", user: @user, projects: @projects %>

ticketee/app/views/admin/users/show.html.erb
<header>
  <h1><%= @user %></h1>

  <ul class="actions">
    <li>
      <%= link_to "Edit User", [:edit, :admin, @user], class: "edit" %>
    </li>
    <li>
      <%= link_to "Archive User", [:archive, :admin, @user], method: :patch,
        data: { confirm: "Are you sure you want to archive this user?"},
        class: "delete" %>
    </li>
  </ul>
</header>

<header>
  <h2>Roles</h2>
</header>

<% if @user.roles.any? %>
  <ul>
    <% @user.roles.each do |role| %>
      <li><%= role.project.name %>: <%= role.role.titleize %></li>
    <% end %>
  </ul>
<% else %>
  <p>This user has no roles.</p>
<% end %>